language: python
matrix:
  include:
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 
         PLAT=manylinux2010_x86_64
         PIP=pip3 
         CIBW_BEFORE_BUILD="pip install pybind11; yum -y install boost-devel"
    python: 3.6
  - os: osx
    language: generic
    env: PIP=pip3
    python: 3.6
  - os: windows
    language: shell
    before_install:
    - choco install python3 --version 3.6.8 --no-progress -y
    - choco install boost-msvc-12 --no-progress -y
    env:
    - PATH=/c/Python36:/c/Python36/Scripts:$PATH 
      PIP=pip3

install: pip --version
env:
  global:
  - TWINE_USERNAME: "__token__"
  - CIBW_BUILD: cp3?-*
  - CIBW_SKIP: "'*-win32 *-manylinux_i686'"
  - CIBW_BEFORE_BUILD: "'pip install pybind11'"
script:
- "$PIP install cibuildwheel==1.0.0"
- cibuildwheel --output-dir wheelhouse
- ls -l wheelhouse
- |
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*.whl
    
